cadastrodj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('funcionario/',include('funcionarios.urls',namespace='funcionario'))
]

funcionarios/urls.py
from django import VERSION
from django.urls import path
from . import views

app_name='funcionario'

urlpatterns=[
    path('todos/',views.listar_funcionarios,name='listar_funcionarios'),
    path('cadastrar/',views.cadastrar_funcionario,name='cadastrar_funcionario'),
    path('detalhes/<int:id>/',views.detalhes_funcionario,name='detalhes_funcionario'),
    path('excluir/<int:id>/',views.excluir_funcionario,name='excluir_funcionario'),
    path('editar/<int:id>/',views.editar_funcionario,name='editar_funcionario')
]

funcionarios/models.py
from django.db import models

# Create your models here.
class Funcionario(models.Model):
    sexo_op=(
        ('masculino','Masculino'),
        ('feminono','Feminino'),
    )
    nome = models.CharField(max_length=150)
    data_nascimento= models.DateField()
    cargo = models.CharField(max_length=100)
    sexo = models.CharField(choices=sexo_op,max_length=20)
    email = models.EmailField()
    telefone = models.CharField(max_length=20)


    def __str__(self) -> str:
        return self.nome

funcionarios/forms.py
from django import forms
from django.forms.fields import DateField
from .models import Funcionario
from cadastrodj import settings

class FuncionarioForm(forms.ModelForm):
    data_nascimento=DateField(input_formats=settings.DATE_INPUT_FORMATS,help_text='d-m-yyyy Ex:07-08-1997')
    class Meta:
        model = Funcionario
        fields = '__all__'

funcionarios/views.py
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render, resolve_url
from .models import Funcionario
# Create your views here.
from .forms import FuncionarioForm

def editar_funcionario(request,id):
    funcionario= get_object_or_404(Funcionario,id=id)
    if request.method=='POST':
        funcionario = FuncionarioForm(request.POST,instance=funcionario)
        if funcionario.is_valid():
            funcionario.save()
            return redirect('funcionario:listar_funcionarios')
        else:
            return HttpResponse('Erro ao editar funcionario')
    funcionario = FuncionarioForm(instance=funcionario)
    context={
        'funcionario':funcionario
    }
    return render(request,'funcionario/editar.html',context)
    
def cadastrar_funcionario(request):
    if request.method =='POST':
        form =FuncionarioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('funcionario:listar_funcionarios')
        return HttpResponse('Erro ao realizar o cadastro ')
    form = FuncionarioForm()
    context = {
        'form':form,
    }

    return render (request,'funcionario/cadastrar.html',context)


def listar_funcionarios (request):
    funcionarios = Funcionario.objects.all()
    context={
        'funcionarios':funcionarios,
    }
    return render(request,'funcionario/listar.html',context)


def detalhes_funcionario(request,id):
    funcionario = Funcionario.objects.get(id=id)
    context = {
        'funcionario':funcionario,
    }
    return render (request,'funcionario/detalhes.html',context)

def excluir_funcionario(request,id):
    funcionario = get_object_or_404(Funcionario,id=id)
    funcionario.delete()
    return redirect('funcionario:listar_funcionarios')

funcionarios/templates/base/model.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>  
<title>Funcionarios App</title>
</head>
<body>
    {% include 'base/navbar.html' %}
    
    {% block content%}





    {% endblock %}
</body>
</html>

funcionarios/templates/base/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Funcionarios Nomade </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'funcionario:listar_funcionarios' %}">Listar Funcionarios </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'funcionario:cadastrar_funcionario' %}">Cadastrar Funcionarios </a>
          </li>
          <!--
          <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        -->
        </ul>
      </div>
    </div>
  </nav>

funcionarios/templates/funcionario/cadastrar.html
{% extends 'base/model.html' %}
{% load bootstrap %}

{% block content %}

<div class="container ">

    <div class="col-md-7 mt-3">
        <h3 class="fs-3 mt-4"> CADASTRAR FUNCIONARIO </h3>

        <div>
                <form action="" method="post">
                    {% csrf_token %}
                    
                    {{form|bootstrap}}
                    

                    <button type="submit" class="btn btn-outline-primary mt-2"  >Cadastrar </button>
                </form>

        </div>


    </div>



</div>



{% endblock %}

funcionarios/templates/funcionario/detalhes.html
{% extends 'base/model.html' %}

{% block content %}

<div class="col-md-8 mx-auto mt-4">
    <h2 class="fs-2 mt-5"> Informações do funcionario {{funcionario.nome}} </h2>

    <table class="table mt-4 ">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Cargo</th>
                <th>Sexo</th>
                <th>Telefone</th>
                <th>Email </th>
                <th>Data Nascimento</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>
                    {{funcionario.nome}}
                </th>
                <th>{{funcionario.cargo}}</th>
                <th>
                    {{funcionario.sexo}}
                </th>
                <th>{{funcionario.telefone}}</th>
                <th>
                    {{funcionario.email}}
                </th>
                <th>{{funcionario.data_nascimento}}</th>
                <th>
                    <a class="btn btn-outline-danger" href="{% url 'funcionario:excluir_funcionario' funcionario.id %}"> Excluir </a>
                </th>
                <th><a class="btn btn-outline-warning" href="{% url 'funcionario:editar_funcionario' funcionario.id %}">Editar </a>
                </th>
            </tr>
        </tbody>


    </table>



</div>
{% endblock %}

funcionarios/templates/funcionario/editar.html
{% extends 'base/model.html' %}
{% load bootstrap %}

{% block content %}

<div class="container ">

    <div class="col-md-7 mt-3">
        <h3 class="fs-3 mt-4">  EDITAR  FUNCIONARIO </h3>

        <div>
                <form action="" method="post">
                    {% csrf_token %}
                    
                    {{funcionario|bootstrap}}
                    

                    <button type="submit" class="btn btn-outline-warning mt-2"  > EDITAR </button>
                </form>

        </div>


    </div>



</div>



{% endblock %}

funcionarios/templates/funcionario/listar.html
{% extends 'base/model.html' %}


{% block content %}

    <div class="col-md-8 mx-auto mt-4">
        <h2 class="fs-2 mt-5"> Lista de Funcionario </h2>

        <table class="table mt-4 ">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Cargo</th>
                    <th>Sexo</th>
                    <th>Telefone</th>
                </tr>
            </thead>
            <tbody>
                {% for funcionario in funcionarios %}
                <tr>
                    <th>
                        {{funcionario.nome}}
                    </th>
                    <th>{{funcionario.cargo}}</th>
                    <th>
                        {{funcionario.sexo}}
                    </th>
                    <th>{{funcionario.telefone}}</th>
                    <th>
                        <a href="{% url 'funcionario:detalhes_funcionario' funcionario.id %}" class="btn btn-outline-success"> Ver Detalhes  </a>
                    </th>
                </tr>
            </tbody>

            {% endfor %}

        </table>



    </div>





{% endblock %}